version: '2'
services:
  feedback-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: feedback-db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: sa
    ports:
      - 3308:3306
  feedback-ms:
    image:  baangaritar/1e-videos-feedback-ms
    ports:
      - 3004:3004
    depends_on:
      - feedback-db
  untube-api:
    image: baangaritar/1e-videos-api-gateway
    environment:
      COURSES_ENTRY: feedback/resources/commentaries
      COURSES_PORT: '3004'
      COURSES_URL: 35.231.49.108
      PORT: '5000'
      SHOW_URLS: 'true'
    ports:
    - 5000:5000/tcp

#1E-UNTube-application