version: '2'
services:
  feedback-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: feedback-db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: sa
    ports:
      - 3308:3306
  feedback-ms:
    image:  baangaritar/1e-videos-feedback-ms
    ports:
      - 3304:3004
    depends_on:
      - feedback-db

#1E-UNTube-application